#!/bin/sh
NO_COLOR="\033[0m"
GREEN="\033[38;5;010m"
YELLOW="\033[38;5;011m"

printf "\n${GREEN}pre commit hook start${NO_COLOR}\n"

PRETTIER="./node_modules/prettier/bin-prettier.js"

if [ -x "$PRETTIER" ]; then
    git status --porcelain | grep -e '^[AM]\(.*\).[js|yml|md|css|scss|json]$' | cut -c 3- | while read line; do
        ${PRETTIER} --write ${line};
        git add "$line";
    done
else
    echo ""
    printf "${YELLOW}Please install prettier, e.g.:${NO_COLOR}"
    echo ""
    echo "  npm install"
    echo ""
fi

printf "\n${GREEN}pre commit hook finish${NO_COLOR}\n"