name: Node.js CI

on:
    push:
        paths-ignore:
            - "**/*.md"
    pull_request:
        paths-ignore:
            - "**/*.md"

jobs:
    build:
        runs-on: ubuntu-latest
        if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: npm install

            - name: Check Style
              run: npm run check-formatting

            - name: Compile Front-end
              run: npm run compile
